package com.tkkj.tkeyes.DataBase;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.tkkj.tkeyes.model.User;
import com.tkkj.tkeyes.model.FramModel;

import com.tkkj.tkeyes.DataBase.UserDao;
import com.tkkj.tkeyes.DataBase.FramModelDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDaoConfig;
    private final DaoConfig framModelDaoConfig;

    private final UserDao userDao;
    private final FramModelDao framModelDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        framModelDaoConfig = daoConfigMap.get(FramModelDao.class).clone();
        framModelDaoConfig.initIdentityScope(type);

        userDao = new UserDao(userDaoConfig, this);
        framModelDao = new FramModelDao(framModelDaoConfig, this);

        registerDao(User.class, userDao);
        registerDao(FramModel.class, framModelDao);
    }
    
    public void clear() {
        userDaoConfig.clearIdentityScope();
        framModelDaoConfig.clearIdentityScope();
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public FramModelDao getFramModelDao() {
        return framModelDao;
    }

}
